### ISSUE TITLE
How to change the current open Collapsible programmatically?

### ISSUE THREAD

**Issue by horcrux2301** [glennflanagan/react-responsive-accordion#15]
I am adding new collapsible components into the Accordion view dynamically. However when a new collapsible is added I want to close the current opened Collapsible and open the new added one. 

I tried using `onTriggerClick ` function mentioned in Readme, but couldn't get it to work. How can I achieve this functionality?

Also in `src/Accordion.js` file the prop is mentioned as `onTrigerClick`  instead of `onTriggerClick` .

**Comment by gatesyp** [comment]
Hi, I've fixed the typo in my own fork and still get the same issue. onTriggerClick is not found as a function: 

```
TypeError: this.props.onTriggerClick is not a function
handleTriggerClick
src/Accordion.js:53
  50 |     closeAll: closeAll,
  51 |   });
  52 |   
> 53 |   this.props.onTriggerClick(position);
  54 | },
  55 | 
  56 | render: function() {
```

**Comment by gatesyp** [comment]
Apologies, forgot to have my function accept the 'position' variable. 

```
  handleAccordionChange(position) {
    alert("HELLO" + position);
  }
```

```
            <Accordion style={{ }} onTriggerClick={this.handleAccordionChange}>
```

Along with fixing the typo, onTriggerClick function works as intended now.
