### ISSUE TITLE
Error on implementing accordion on ionic/react

### ISSUE THREAD

**Issue by kevinpallado** [glennflanagan/react-responsive-accordion#19]
I've tried your collapsible on earlier and it runs smooth, and when I tried to test accordion on the same code. I got something error `Could not find a declaration file for module 'react-responsive-accordion'. 'c:/development/ionic/books/node_modules/react-responsive-accordion/dist/Accordion.js' implicitly has an 'any' type.
  Try `npm install @types/react-responsive-accordion` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-responsive-accordion';`

npm version 6.14.5

dependencies

`"dependencies": {
    "@capacitor/core": "2.2.0",
    "@ionic/react": "^5.0.7",
    "@ionic/react-router": "^5.0.7",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^8.0.3",
    "@types/jest": "^24.0.25",
    "@types/node": "^12.12.24",
    "@types/react": "^16.9.17",
    "@types/react-dom": "^16.9.4",
    "@types/react-router": "^5.1.4",
    "@types/react-router-dom": "^5.1.3",
    "autoprefixer": "^9.8.0",
    "ionicons": "^5.0.0",
    "react": "^16.13.0",
    "react-collapsible": "^2.8.0",
    "react-dom": "^16.13.0",
    "react-responsive-accordion": "^1.0.0",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1",
    "typescript": "3.8.3"
  }`

**Comment by glennflanagan** [comment]
You're using typescript and this library has no typescript definitions. You need to declare your own or stub it out as says 

```
add a new declaration (.d.ts) file containingdeclare module 'react-responsive-accordion';`
```
