### ISSUE TITLE
Got error when there is only one item

### ISSUE THREAD

**Issue by yuchuan1** [glennflanagan/react-responsive-accordion#4]
When there is only one item within Accordion, an error occurs.
<Accordion>
          
          <div data-trigger="Test" >
            <p>this is a test</p>
          </div>

        </Accordion>`
**Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Accordion`, expected an array.**

**Comment by glennflanagan** [comment]
I've not updated this code in a while but if you are just having one item in the accordion then it's not an accordion and you will want to use Collapsible on it's own https://github.com/glennflanagan/react-collapsible
